### ISSUE TITLE
Does not support colon-delimited "flavor" of 24-bit "truecolor" escape sequences.

### ISSUE THREAD

**Issue by jaysonlarose** [pycontribs/ansi2html#166]
Hello!

I'm the one who originally submitted #101 . (Thank you so much for implementing that!) @hartwork asked me to submit a new report for this issue, so here it is. They asked for some additional information, such as what apps I've seen that produce this form of ANSI output, terminals used, et cetera...  So this issue comes in two parts — The first being a description of the two different methods in use for specifying 24-bit color codes, and the second part being story time.

# 24 Bit Color Ansi Terminal Escape Codes — Why Have One Method When You Can Have Two?

Thank you @trygveaaa for pointing [this document](https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_) out to me. It's the Xterm spec which describes this alternate escape sequence method. They claim that using the colon is the standard. [One might argue that whichever version has the most implementations is the standard](https://github.com/termstandard/colors#truecolor-support-in-output-devices), but I digress.

The good news is that the only difference between the two is that one uses semicolons as a delimiter between elements of the terminal sequence, and the other uses colons. I've seen an exception to this, however: when foreground and background specifiers are combined in the same control sequence, I've seen a semicolon being used to separate the two components of the sequence, like this:

```
<exc> [ 38 : 2 : 0 : 0 : 255 ; 48 : 2 : 255 : 255 : 0 m
```

I'd say that the most compatible way of doing it is to treat any occurence of colon or semicolon as a valid delimiter character, at least when dealing with "38;2" / "39;2" color codes.

Examples!

```python
#!/usr/bin/env python3

colon_block = "Roses are \x1b[38:2:255:0:0mred\n\x1b[38:2:0:0:255;48:2:255:255:0mThis background is yellow\n\x1b[39;49mI can't \x1b[38:2:255:255:255;48:2:0:0:255mthink\x1b[39;49m of a rhyme\n\x1b[38:2:254:254:254m(I'm \x1b[38:2:216:216:216mnot \x1b[38:2:178:178:178ma \x1b[38:2:140:140:140msmart \x1b[38:2:102:102:102mfellow...)\x1b[m\n"

semicolon_block = "Roses are \x1b[38;2;255;0;0mred\n\x1b[38;2;0;0;255;48;2;255;255;0mThis background is yellow\n\x1b[39;49mI can't \x1b[38;2;255;255;255;48;2;0;0;255mthink\x1b[39;49m of a rhyme\n\x1b[38;2;254;254;254m(I'm \x1b[38;2;216;216;216mnot \x1b[38;2;178;178;178ma \x1b[38;2;140;140;140msmart \x1b[38;2;102;102;102mfellow...)\x1b[m\n"

if __name__ == '__main__':
	print(colon_block)
	print(semicolon_block)
```

Documents!

<https://github.com/termstandard/colors>

I consider this to be the source of truth on 24-bit ANSI color codes, because its predecessor (<https://gist.github.com/XVilka/8346728>) was the first source I found on the matter, and that the author(s) have gone through the trouble of keeping track of which terminal emulators support 24-bit color, and what methods they use to do it.

<https://en.wikipedia.org/wiki/ANSI_escape_code#Colors>

This Wikipedia article is referenced by the first document, and contains useful information as well.

<https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h3-Functions-using-CSI-_-ordered-by-the-final-character_s_>

The Xterm spec that @trygveaaa brought to my attention. This is important because it describes how colon-delimited ANSI codees are implemented in reality, as opposed to the next document:

<https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-T.416-199303-I!!PDF-E&type=items>

, which can also be found by Googling for "itu t.416". I only include this document as it's referred to as the basis that the colon-delimited format was derivative of.

# Story Time

I've been looking for a better terminal emulator for Linux for over a decade now. I've got a laundry list of things I need in a terminal emulator, and every couple of years or so, I take this list of requirements out, dust it off, and try out the various terminal emulators to see if there's a new king of the hill. For the past several times I've done this, the terminal I settled with was Gnome-Terminal. It has a nasty habit of crashing whenever you try to copy and paste too much text. This could be mitigated as long as you were careful... it's no iTerm2, but it's workable.

Over the years I'd spent using this terminal emulator, there came one option that I came to rely on that I haven't seen anywhere else — You can get it to copy text to the clipboard with embedded HTML codes for setting foreground and background color! This allows me to create documents that show color-accurate command output that you can copy and paste from, and take up a lot less space than a screenshot.

So terminal emulator gladiator time came again, and I start evaluating this new whipper snapper on the block, [kitty](https://sw.kovidgoyal.net/kitty/). It checks almost all the boxes, and supports enough remote control/automation that I can probably make up the difference. It even allows you to pull colored text out of it! But, sadly, it's using ANSI color codes instead of HTML, and I hadn't yet found a library that allows me to convert between the two. There was this one Python library that I submitted a bug report to, but I didn't have high hopes of anyone getting around to it. But then they did! Or rather, you did! You added 24-bit color support!

I'm starting to feel pretty stoked. I might finally get out of this bad relationship with Gnome Terminal. The hours and hours of work it's lost me when I accidentally try to copy too much text and it crashes, meaning I lose ALL of my active terminal sessions.... I try out kitty's "get-text" function, and it seems to work, except that when you try to get the currently selected text, it comes over without ANSI codes, for some reason beyond my understanding. So in a long shot, I ask the developer to add a "copy to clipboard with ANSI" command... and he does! It looks like it works!

The pieces are all coming together, I just have to copy text out of the terminal, run it through your library, and I can kick Gnome-Terminal to the curb. It's time for the inaugural run. The sun comes out, crepuscular rays bathing the world in glorious light. Angels begin singing, birds are chirping, et cetera. I highlight a bunch of text, hit the hotkey to toss it into the clipboard, and then run it through ansi2html... and nothing happens.

I start looking through the output from the terminal emulator, and what's this? Colons? Why are there colons? I go back and look at the [docs](https://github.com/termstandard/colors), and that's when I notice this little blurb about delimiters. Hunh. I poke around a bit in the terminal emulator's code, and find the part that's doing the ANSI export. A two-line change to the code, and I'm in business! I ask the developer of the terminal emulator if he'd add an configuration option for specifying what flavor of ANSI to use, and he comes back with "No. colons are the correct way to do it".

Now, I'm not about to argue with the guy that implemented this function for me, especially when I've got a workaround in place already... but, if you go by implementation count, semicolons are the more popular method. This reminds me of a tale of a man, a wise man, but still a man, who invented a method for compressing images. It was a wonderful format, and everyone loved it, until it came time to talk about it out loud with others. There was a great rift among the people about how to pronounce it. Was it with a "guh", like "graphics"? Or was it with a "juh", like "jerk"? Many wars were fought across the Internets about this, and finally the people asked, "What did the man who invented it say"? He spoke his opinion, and the moral we all learned that day was that you can be the person who created something, and still be wrong about it.

What was I talking about again? Oh yeah. Terminal codes. I've got the thing I need in order to bid myself good riddance of Gnome-Terminal, but I'd _really_ like to not have to carry along yet another custom source patch around until the end of time. So I'm hoping you'll humor me, and implement the losing-yet-correct-according-to-some alternate implementation of these ANSI color codes. 

And they all lived happily ever after.

**Comment by trygveaa** [comment]
So the standard terminal emulators use for control codes is [ECMA-48](https://www.ecma-international.org/wp-content/uploads/ECMA-48_5th_edition_june_1991.pdf). However, for these RGB sequences it says:

```
38 (reserved for future standardization; intended for setting character foreground colour as specified in
   ISO 8613-6 [CCITT Recommendation T.416])
48 (reserved for future standardization; intended for setting character background colour as specified in
   ISO 8613-6 [CCITT Recommendation T.416])
```

I haven't read ISO 8613-6 since you have to buy it, but T.416 is supposed to be the same. [T.416](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-T.416-199303-I!!PDF-E&type=items) says:

```
The parameter values 38 and 48 are followed by a parameter substring used to select either the character foreground
“colour value” or the character background “colour value”.
A parameter substring for values 38 or 48 may be divided by one or more separators (03/10) into parameter elements,
denoted as Pe. The format of such a parameter sub-string is indicated as:
        Pe : P ...
```

So it seems correct to me that xterm and kitty is indeed correct that colon is the correct separator to use. However, I wondered why KDE Konsole went with semicolon so I searched and found [this](https://github.com/KDE/konsole/blob/master/doc/user/README.moreColors) which says:

```
A note on conformance

These ESC codes break the "associativity" of SGR, but after some
research the result is, that the standard itself is broken here.

The perhaps best codes due to ECMA-48 would probably be e.g.
38:2:<r>:<g>:<b>, i.e. consistently a colon instead of a semicolon.
But apparently, this is defined different in ISO-8613 (which is
included at this place in ECMA-48), actually breaking ECMA-48.

We cannot help this and implemented the codes as above, which
is a balanced decision.
```

I can't understand this reasoning however, because as far as I can see it's not defined different in ISO-8613. It uses colon (at least if T.416 is indeed the same as ISO-8613), which they state is what fits with ECMA-48. So I'm not sure how KDE Konsole reached this conclusion. They say "apparently, this is defined different", so maybe they haven't read the standard but just been told it incorrectly.

Either way, the harm is done and we now have two different ways to do it. For some reason, the majority seem to have gone with the way KDE Konsole does it, not the way xterm (and the standard as far as I can see) does it.

If you were to produce these sequences, you'd have to settle on one or give an alternative, which could probably be lengthy debated, but luckily you are only parsing these sequences in this library. When parsing, it seems to me that the only sane option is to support both sequences, like many terminal emulators already do.

**Comment by trygveaa** [comment]
> I can't understand this reasoning however, because as far as I can see it's not defined different in ISO-8613. It uses colon (at least if T.416 is indeed the same as ISO-8613), which they state is what fits with ECMA-48. So I'm not sure how KDE Konsole reached this conclusion. They say "apparently, this is defined different", so maybe they haven't read the standard but just been told it incorrectly.

I searched some more and found the [original request for adding support in Konsole](https://bugs.kde.org/show_bug.cgi?id=107487) and a [bug requesting support for colons](https://bugs.kde.org/show_bug.cgi?format=multiple&id=329639), and understood how this came to be. Xterm originally implemented it with semicolons, not colons, because the author read the standard wrong. That this was wrong was caught in the process of implementing it in Konsole, but they went with the same as xterm. This explains why semicolon is the most prevalent. Xterm later added support for colon as well, but Konsole has not.

This is probably way more info than you needed, but I was curious :) I stand by what I said in the previous comment that any parsing should support both. Note that the example in the original post with both foreground and background being defined in the same sequence is also perfectly valid since SGR parameters can be combined:

```
<esc> [ 38 : 2 : 0 : 0 : 255 ; 48 : 2 : 255 : 255 : 0 m
```

This is what the Konsole doc meant when they said "These ESC codes break the "associativity" of SGR", since combining multiple parameters is not possible when using semicolons to separate the arguments for 38 and 48. But when colons are used, this library should support parsing this as well.

**Comment by trygveaa** [comment]
> This is what the Konsole doc meant when they said "These ESC codes break the "associativity" of SGR", since combining multiple parameters is not possible when using semicolons to separate the arguments for 38 and 48. But when colons are used, this library should support parsing this as well.

Actually, both xterm and kitty supports combining multiple SGR parameters when using semicolons to delimit 38 and 48 too. Associativity is broken (you can't reorder the parameters, 2 and then the rgb values has to follow 38/48), but you can still support combinations by knowing that 38/48 always has four extra parameters. (Actually, it has five according to the standard, there should be a color space identifier between 2 and the rgb values, but this is never included when using semicolons as delimiters, and often omitted when using colon as delimiters as well).

**Comment by jaysonlarose** [comment]
I'm not sure how to properly associate it with this issue, but I submitted a pull request with a real quick and dirty hack for this.   It should be the thing mentioned right above this message?
